repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables

  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982"
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--no-strict-optional, --ignore-missing-imports]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
